### ISSUE TITLE
Multiple participants of the same team have the same predicted role

### ISSUE THREAD

**Issue by ValerianRey** [Canisback/roleML#19]
Most of the times (99%+) this does not happen, but for example in match with id 4689775875 (region EUW), after using add_cass_predicited_roles I get the following roles:

blue side:
- Senna has predicted role: supp
- Nocturne has predicted role: bot
- Kayn has predicted role: jungle
- Ezreal has predicted role: top
- Ekko has predicted role: top
 
red side:
- Varus has predicted role: bot
- Zoe has predicted role: mid
- Karma has predicted role: supp
- Shen has predicted role: top
- Nidalee has predicted role: jungle

The problem is that 2 players from blue team have the same predicted role (Ezreal and Ekko are predicted as top), and thus no one is predicted as mid. Shouldn't there always be 5 distinct roles per team? If not how can we enforce it?

The composition of blue team is a bit unusual but except for Ezreal, the predicted roles are the same as on op.gg.

Thanks in advance!

**Comment by Canisback** [comment]
There is not always the 5 roles in a game, so it's not enforced and all predictions are independant from one another. You just encountered a case of swaplane, both Ekko and Ezreal spending half the early game toplane, the other half midlane, hence a confusion and no final answer, as it depends on everyone opinion on that matter.

I tried to force the 5 roles per team but it only brought more errors so I don't plan to dig further that way.

**Comment by ValerianRey** [comment]
Ok thanks for the quick answer! It would definitely be a cool feature to have that as a parameter (enforce distinct roles true/false). On my side I don't really need it yet though since I can just drop the matches where this kind of things happens.
