### ISSUE TITLE
Classifies every participant as either jungle/supp

### ISSUE THREAD

**Issue by ggrochow** [Canisback/roleML#5]
In testing to see if this would work for my use-case, I was unable to get recent matches to report anything other than jungle or support for roles.

I tested this against about 5-10 different games, but no roles other than jungle/supp showed up in the results. This even occurs when testing against gameIds in the verification_results.csv 

This is the code I was using for testing.
```python
from roleml import roleml
import requests

region = 'euw1'
match_id = '4151988491'

params = {
    'api_key': '_____'
}

match_url = 'https://{0}.api.riotgames.com/lol/match/v4/matches/{1}'.format(region, match_id)
match_res = requests.get(match_url, params=params)
match_json = match_res.json()

timeline_url = 'https://{0}.api.riotgames.com/lol/match/v4/timelines/by-match/{1}'.format(region, match_id)
timeline_res = requests.get(timeline_url, params=params)
timeline_json = timeline_res.json()

roles = roleml.predict(match_json, timeline_json)

print(roles)
# {1: 'jungle', 2: 'supp', 3: 'jungle', 4: 'supp', 5: 'supp', 6: 'supp', 7: 'supp', 8: 'jungle', 9: 'supp', 10: 'jungle'}
```

**Comment by Canisback** [comment]
This code returns to me 
`{1: 'top', 2: 'jungle', 3: 'mid', 4: 'bot', 5: 'supp', 6: 'supp', 7: 'bot', 8: 'top', 9: 'jungle', 10: 'mid'}`
Can you send the versions of modules you use for roleml, scikit-learn, pandas and numpy?

**Comment by ggrochow** [comment]
using `pip show____ `
```
Name: roleml
Version: 0.1.8

Name: scikit-learn
Version: 0.21.3

Name: pandas
Version: 0.25.0

Name: numpy
Version: 1.17.0
```

Fresh install of 64 bit python 3.7.4 python on windows, and pip install roleml requests 

I could have very easily done something strange in this process though, I'm not knowledgeable in python

**Comment by Canisback** [comment]
Found the culprit, it's caused by pandas and its 0.25 version.

Try installing an older version with
`pip install pandas==0.24.2`
It should fix the problem until I upgrade to the latest version.

**Comment by ggrochow** [comment]
Confirming that this does solve my issue, tested against a few games in the verification set and some from a recent patch. Thanks for the quick reply & assistance. 
Leaving this open for you to close whenever you've done said upgrade.
