### ISSUE TITLE
sklearn joblib deprecation

### ISSUE THREAD

**Issue by tsevenhuysen** [Canisback/roleML#6]
When I call the module I get the following warning:

"DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)"

Can the module be updated so that it won't break when the next version of sklearn comes out?

**Comment by Canisback** [comment]
I made a new dataset for verification to see how the classifier handles new patches data.
I will update sklearn at the same time, so expect it to come soon.

**Comment by tsevenhuysen** [comment]
> I made a new dataset for verification to see how the classifier handles new patches data.
> I will update sklearn at the same time, so expect it to come soon.

Sounds great!
