### ISSUE TITLE
timeline diff calculations use index instead of participantId

### ISSUE THREAD

**Issue by tsevenhuysen** [Canisback/roleML#7]
On lines 260 to 270 of roleml.py, an assumption is made that in the participantFrames array, the key for each item matches the participantId. That's not always the case.

It's necessary to enter each item and get the participantId to make sure the correct timeline diffs get calculated.

Here's an example of what participantFrames can sometimes look like (note that index 0 (key '1') is for participantId 4.

`{'1': {'participantId': 4, 'position': {'x': 1432, 'y': 11199}, 'currentGold': 823, 'totalGold': 2923, 'level': 7, 'xp': 3629, 'minionsKilled': 41, 'jungleMinionsKilled': 0, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': -314, 'xpDiff': -727, 'minionsKilledDiff': -31, 'jungleMinionsKilledDiff': 0},
  '2': {'participantId': 5, 'position': {'x': 2073, 'y': 1161}, 'currentGold': 46, 'totalGold': 3121, 'level': 6, 'xp': 2783, 'minionsKilled': 3, 'jungleMinionsKilled': 20, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': -302, 'xpDiff': 66, 'minionsKilledDiff': -44, 'jungleMinionsKilledDiff': 20},
  '3': {'participantId': 1, 'position': {'x': 6171, 'y': 5751}, 'currentGold': 763, 'totalGold': 3138, 'level': 8, 'xp': 4210, 'minionsKilled': 58, 'jungleMinionsKilled': 0, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': 695, 'xpDiff': 1434, 'minionsKilledDiff': 45, 'jungleMinionsKilledDiff': 0},
  '4': {'participantId': 3, 'position': {'x': 13535, 'y': 3944}, 'currentGold': 631, 'totalGold': 4206, 'level': 7, 'xp': 3515, 'minionsKilled': 77, 'jungleMinionsKilled': 4, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': 788, 'xpDiff': -422, 'minionsKilledDiff': 20, 'jungleMinionsKilledDiff': 4},
  '5': {'participantId': 2, 'position': {'x': 13442, 'y': 3933}, 'currentGold': 1128, 'totalGold': 2888, 'level': 6, 'xp': 2889, 'minionsKilled': 5, 'jungleMinionsKilled': 0, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': -514, 'xpDiff': -374, 'minionsKilledDiff': -2, 'jungleMinionsKilledDiff': -48},
  '6': {'participantId': 6, 'position': {'x': 2044, 'y': 11767}, 'currentGold': 193, 'totalGold': 3418, 'level': 7, 'xp': 3937, 'minionsKilled': 57, 'jungleMinionsKilled': 0, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': -788, 'xpDiff': 422, 'minionsKilledDiff': -20, 'jungleMinionsKilledDiff': -4},
  '7': {'participantId': 10, 'position': {'x': 13943, 'y': 4872}, 'currentGold': 623, 'totalGold': 3423, 'level': 6, 'xp': 2717, 'minionsKilled': 47, 'jungleMinionsKilled': 0, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': 302, 'xpDiff': -66, 'minionsKilledDiff': 44, 'jungleMinionsKilledDiff': -20},
  '8': {'participantId': 8, 'position': {'x': 7607, 'y': 7600}, 'currentGold': 212, 'totalGold': 3237, 'level': 8, 'xp': 4356, 'minionsKilled': 72, 'jungleMinionsKilled': 0, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': 314, 'xpDiff': 727, 'minionsKilledDiff': 31, 'jungleMinionsKilledDiff': 0},
  '9': {'participantId': 9, 'position': {'x': 3193, 'y': 7278}, 'currentGold': 477, 'totalGold': 3402, 'level': 7, 'xp': 3263, 'minionsKilled': 7, 'jungleMinionsKilled': 48, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': 514, 'xpDiff': 374, 'minionsKilledDiff': 2, 'jungleMinionsKilledDiff': 48},
  '10': {'participantId': 7, 'position': {'x': 14227, 'y': 13131}, 'currentGold': 43, 'totalGold': 2443, 'level': 6, 'xp': 2776, 'minionsKilled': 13, 'jungleMinionsKilled': 0, 'dominionScore': 0, 'teamScore': 0, 'totalGoldDiff': -695, 'xpDiff': -1434, 'minionsKilledDiff': -45, 'jungleMinionsKilledDiff': 0}}`

**Comment by Canisback** [comment]
This mismatch has been fixed in the main part but not there, see here for the fix : 
https://github.com/Canisback/roleML/commit/bd033e28438a24d45a7a16e69db0c13c02e81312

Thanks for your feedback.
